# Generated by Django 5.2.5 on 2025-08-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_table',
            name='price',
            field=models.IntegerField(default=100),
        ),
    ]
