# Generated by Django 5.2 on 2025-08-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_main_table_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='age',
            field=models.CharField(default='hello', max_length=50),
        ),
    ]
