# Generated by Django 5.2 on 2025-09-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_categories_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_table',
            name='age',
        ),
        migrations.AddField(
            model_name='main_table',
            name='hello',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
